version: "3.9"  # optional since v1.27.0
services:
  ml_app:
    container_name: ml_app_1_4
    tty: true
    image: leonardocoutoc/python:mlapp1.4-release
    depends_on:
      mysql_ml_app_db:
        condition: service_healthy
    working_dir: /opt/ml_app/ML
    command: sh start_ml_app.sh
    networks:
      - mysql-python-network

  mysql_ml_app_db:
    container_name: mysql_ml_app_db
    image: mysql:8.0
    tty: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123senha
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 3s
      interval: 3s
      timeout: 5s
      retries: 55
    ports:
      - '3306:3306'
    networks:
      - mysql-python-network
networks:
  mysql-python-network: