version: "3.9"  # optional since v1.27.0
services:
  ml_app_12:
    container_name: ml_app_1_2
    tty: true
    image: leonardocoutoc/python:mlapp1.2-release
    depends_on:
      - mysql_ml_app_db
    working_dir: /opt/ml_app/ML
    #command: ["python", "main.py"]
    command: sh -c "sh -c "mysql -u root -p123senha -h mysql_ml_app_db < bds_classification.sql && python main.py"
    networks:
      - mysql-python-network
    
  mysql_ml_app_db:
    container_name: mysql_ml_app_db
    image: mysql:8.0
    tty: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123senha
    ports:
      - '3306:3306'
    networks:
      - mysql-python-network
networks:
  mysql-python-network: